### ISSUE TITLE
Правки в классе Player

### ISSUE THREAD

**Issue by lulabooo** [zlobryak/javaqa-team-project#1]
1. Создать setter для поля name
2. Создать setter playedTime
3. Создать getter playedTime

**Comment by zlobryak** [comment]
1. В классе player, `name ` задается конустроктором  `public Player(String name)`
https://github.com/zlobryak/javaqa-team-project/blob/2071c576662a91340c6e137c16b89d52a6f18dbc/src/main/java/ru/netology/Player.java#L14-L16
2. Новые игры в HashMap `playedTime` добавляются методом `public void installGame(Game game)`
https://github.com/zlobryak/javaqa-team-project/blob/2071c576662a91340c6e137c16b89d52a6f18dbc/src/main/java/ru/netology/Player.java#L24-L26
3. Добавил метод `public int timePlayed(Game game)`
https://github.com/zlobryak/javaqa-team-project/blob/bab10996850a123e6beba50e3a1bea581daf976c/src/main/java/ru/netology/Player.java#L76-L84
4. Для него добавил класс `NoGameExeption` с исключением.
https://github.com/zlobryak/javaqa-team-project/blob/bab10996850a123e6beba50e3a1bea581daf976c/src/main/java/ru/netology/exeptions/NoGameExeption.java#L2-L4
